name:                chess
version:             0.1.0.0
github:              "ignaciomosca/chess"
license:             BSD3
author:              "Ignacio Mosca"
maintainer:          "ignaciomosca@outlook.com"
copyright:           "2018 Ignacio Mosca"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/chess#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- set-extra
- split
- hspec

library:
  source-dirs: src

executables:
  chess-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    dependencies:
    - chess

tests:
  chess-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -O2
    dependencies:
    - chess
